# Generated by Django 3.2.9 on 2021-11-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
